---
  - name: Install epel-release repository for RedHat
    yum: 
      name: epel-release
      state: present
    when: ansible_os_family == "RedHat"

  - name: Install usefull packages for setup a server
    package: 
      name: "{{ item }}"
      state: present
    with_items: "{{ server_packages}}"
