
---
  - name: Install percona repository for mysql
    shell: "yum install -y {{ mysql_rpm_packages.package_repository }}"
    when: ansible_os_family == "RedHat"

  - name: Disable mysql module for RHEL 8
    shell: "dnf module -y disable mysql"
    when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "8"

  - name: Install mysql percona server
    yum: 
      name: "{{ mysql_rpm_packages.package_name }}-{{ mysql_rpm_packages.package_version }}"
      state: present
    when: ansible_os_family == "RedHat"